### ISSUE TITLE
YandexMobileMetrica and Swift 3.1 project

### ISSUE THREAD

**Issue by YurchukV** [yandexmobile/metrica-sample-ios#28]
Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions
https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/tasks/swift-quickstart-docpage/

**Comment by bamx23** [comment]
Thank you! We have fixed the documentation.
