### ISSUE TITLE
Got hamful app-crash on build

### ISSUE THREAD

**Issue by trickyc0d3r** [yandexmobile/metrica-sample-ios#34]
info 10:
/Users/trickuc0d3r/work/xxic/ios/YandexMobileMetrica.framework/Headers/YMMYandexMetrica.h:9:9: fatal error: could not build module 'Foundation'

got this error and need emergency help =(
using react-native 59.1

this is my podfile `# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '21vek' do
  pod 'AppCenter/Push', '~> 1.13.2'
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  pod 'YandexMobileMetrica', '3.5.0'
  pod 'GoogleSignIn'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod "VK-ios-sdk" 
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  platform :ios, '9.0'
  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

  target '21vekTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target '21vek-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 21vek-tvOS

  target '21vek-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end`

**Comment by bamx23** [comment]
Hi! Have you tried this React Native solution for AppMetrica: https://github.com/doochik/react-native-appmetrica ?
You also could try to set `Enable Modules (C and Objective C)` to `NO` (in build settings).
